### PR TITLE
Add apache

### PR DESCRIPTION
**Pull request by jmi4**
Adding the apache 2.2 profile from http://iase.disa.mil/stigs

### CODE REVIEW

**Comment by pburkholder** [comment]
This is cool that you've put this together!

The continual use of this idiom:, `conf_file = command('find / -type f -name httpd.conf').stdout.chomp` gives me pause, since it's a potentially large search and will miss all the  all the files in a `conf.d` setup (and it won't work on Windows, not that that's a likely audience for this.). 

What if this only targeted RHEL style Apache installs, and generated a finding if you're running the check on some other platform?

And, how about if there were a check on the process table to generate a finding if any process matching 'httpd|apache' were using a conf file in a non-standard location (and hence was not subject to the current checks...)?

Maybe we should  think about how we could use test-kitchen to test these against standard installs (e.g: RHEL7 w/ httpd enabled should generate 30 findings....)

Cheers, Peter

**Comment by paulczar** [comment]
Yeah I agree with @pburkholder doing the find is probably overkill,  we should provide a default location(s) to look for apache config files in a list which would cover the default places you'd see config files in rhel/ubuntu and it would be an exercise for the reader to modify the list in their env.

**Comment by jmi4** [comment]
I know I can create an attributes file to specify the location, however, I am not sure how well that will play with Chef Compliance. Using just inspec it is easy to include the --attr <attribute.yml>

I can just make this for RHEL and simply put in /etc/httpd/conf/httpd.conf for the file?
Otherwise would I have to do an if node['platform_family]' statement to determine where the default config file would be?

**Comment by paulczar** [comment]
I'm okay with focussing this on RHEL ...   we can add support for other OSes and use platform_family etc to break it out later.

**Comment by jmi4** [comment]
closing this PR, I will create a repo for this stig

**Pull request closed without merging**
